import { defineStore } from 'pinia';

export const useDashboardStore = defineStore('dashboard', {
  state: () => ({
    summaryStats: [
      {
        id: 1,
        title: 'งานวันนี้',
        count: 12,
        trend: '+2 จากเมื่อวาน',
        trendColor: 'green-6',
        icon: 'assignment',
        iconColor: 'blue-1',
        iconTextColor: 'blue-7',
        status: 'normal',
      },
      {
        id: 2,
        title: 'งานค้างส่ง',
        count: 3,
        trend: 'ต้องการดำเนินการด่วน',
        trendColor: 'red-6',
        icon: 'priority_high', // Changed from warning to priority_high for a cleaner look
        iconColor: 'red-1',
        iconTextColor: 'red-7',
        status: 'urgent', // Used to conditionally show the exclamation mark icon if needed
      },
      {
        id: 3,
        title: 'กำลังดำเนินการ',
        count: 5,
        trend: 'อยู่ในเกณฑ์เวลา',
        trendColor: 'orange-8',
        icon: 'build',
        iconColor: 'orange-1',
        iconTextColor: 'orange-7',
        status: 'warning',
      },
      {
        id: 4,
        title: 'รออนุมัติผล',
        count: 8,
        trend: 'รอหัวหน้างานตรวจสอบ',
        trendColor: 'grey-7',
        icon: 'playlist_add_check',
        iconColor: 'deep-purple-1',
        iconTextColor: 'deep-purple-7',
        status: 'normal',
      },
    ],
    urgentWork: [
      {
        id: 'EQ-2309-001',
        name: 'เครื่องช่วยหายใจ (Ventilator)',
        model: 'รุ่น Servo-i',
        dept: 'ICU 2',
        deptColor: 'red-1',
        deptTextColor: 'red-8',
        status: 'เกินกำหนด',
        statusColor: 'red-7',
        dueDate: '23 ต.ค.',
      },
      {
        id: 'EQ-2305-112',
        name: 'เครื่องติดตามสัญญาณชีพ',
        model: 'Patient Monitor',
        dept: 'ER',
        deptColor: 'orange-1',
        deptTextColor: 'orange-8',
        status: 'ใกล้หมดอายุ',
        statusColor: 'orange-8',
        dueDate: 'วันนี้',
      },
      {
        id: 'EQ-2211-089',
        name: 'เครื่องกระตุกหัวใจ',
        model: 'Defibrillator',
        dept: 'OR 1',
        deptColor: 'blue-1',
        deptTextColor: 'blue-8',
        status: 'รออะไหล่',
        statusColor: 'blue-7',
        dueDate: 'พรุ่งนี้',
      },
      {
        id: 'EQ-2301-055',
        name: 'เครื่องควบคุมการให้สารละลาย',
        model: 'Infusion Pump',
        dept: 'IPD 5',
        deptColor: 'teal-1',
        deptTextColor: 'teal-8',
        status: 'รอส่งมอบ',
        statusColor: 'green-7',
        dueDate: '26 ต.ค.',
      },
      {
        id: 'EQ-2308-011',
        name: 'ตู้อบเด็กแรกเกิด (Incubator)',
        model: 'Drager Isolette 8000',
        dept: 'NICU',
        deptColor: 'purple-1',
        deptTextColor: 'purple-8',
        status: 'ใกล้หมดอายุ',
        statusColor: 'orange-8',
        dueDate: '27 ต.ค.',
      },
      {
        id: 'EQ-2212-042',
        name: 'เครื่องจี้ไฟฟ้า (Electrosurgical Unit)',
        model: 'Covidien Force FX',
        dept: 'OR 3',
        deptColor: 'blue-1',
        deptTextColor: 'blue-8',
        status: 'รอดำเนินการ',
        statusColor: 'grey-7',
        dueDate: '28 ต.ค.',
      },
    ],
    alerts: [
      {
        id: 1,
        title: 'ผลการสอบเทียบไม่ผ่าน',
        description: 'เครื่องกระตุกหัวใจ (Defibrillator) #DF-002 ค่า Energy Output ต่ำกว่าเกณฑ์',
        time: 'ดูรายละเอียด',
        type: 'error' as 'error' | 'info' | 'warning',
      },
      {
        id: 2,
        title: 'ลงทะเบียนครุภัณฑ์ใหม่',
        description: 'แผนก ER เพิ่มเครื่อง Infusion Pump จำนวน 5 เครื่อง',
        time: '10 นาทีที่แล้ว',
        type: 'info' as 'error' | 'info' | 'warning',
      },
      {
        id: 3,
        title: 'แจ้งเตือนสอบเทียบซ้ำ',
        description: 'เครื่อง Ventilator #VN-088 ถึงกำหนด Re-calibration',
        time: '1 ชั่วโมงที่แล้ว',
        type: 'warning' as 'error' | 'info' | 'warning',
      },
    ],
    chartData: [65, 59, 80, 81, 56, 55, 40],
  }),
});
